//
//  MigrationPlan.swift
//  MyToob
//
//  Created by Claude Code (BMad Master) on 11/26/25.
//

import Foundation
import os.log
import SwiftData

/// Migration plan orchestrating schema upgrades.
///
/// ## Current Status: DISABLED
/// Migration is currently disabled because there are no existing users who need migration.
/// The app uses `CurrentSchema` (v2.0.0) with all production models.
///
/// ## How to Enable Migration
/// When migration is needed (e.g., after shipping v1 and creating v2):
/// 1. Create versioned model classes (e.g., `VideoItemV1` for the old structure)
/// 2. Create versioned schema enums (e.g., `SchemaV1`, `SchemaV2`)
/// 3. Add migration stages below
/// 4. Uncomment `migrationPlan: MyToobMigrationPlan.self` in MyToobApp.swift
///
/// ## Schema History
/// - V1 (1.0.0): Initial release with VideoItem, ClusterLabel, Note, ChannelBlacklist
/// - V2 (2.0.0): Added `lastAccessedAt` property to VideoItem
///
/// ## Embedding Dimension Change (384 → 512)
/// The embedding dimension change from 384 (legacy Core ML model) to 512
/// (Apple NLEmbedding) does NOT require a schema migration since the underlying
/// storage type (`embeddingData: Data?`) is unchanged. Instead, embeddings are
/// lazily regenerated by the AI pipeline when accessed.
enum MyToobMigrationPlan: SchemaMigrationPlan {

  // MARK: - Private

  private static let logger = Logger(subsystem: "com.mytoob.app", category: "migration")

  // MARK: - Schema History

  /// All schemas in chronological order (oldest first).
  /// SwiftData uses this to determine the migration path.
  ///
  /// Currently only contains the current schema since migration is disabled.
  /// When adding migrations, list all schema versions here.
  static var schemas: [any VersionedSchema.Type] {
    [CurrentSchema.self]
  }

  // MARK: - Migration Stages

  /// All migration stages in order of execution.
  ///
  /// Currently empty since migration is disabled.
  /// Add stages here when migrating between schema versions.
  static var stages: [MigrationStage] {
    []
  }
}
